version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: prisma_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
